name: SSH into remote server

# on:
#   workflow_run:
#     workflows: ["Spin up a runner"]
#     types:
#       - completed
on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          ls ~/.ssh -al
          ssh-keyscan -H echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      #   run: |
      #     echo "${{ secrets.PASSPHRASE }}" | \
      #     mkdir -p ~/.ssh
      #     eval `ssh-agent -s`
      #     ssh-add <(echo "${SSH_PRIVATE_KEY}" | base64 --decode | tr -d "\r")
      #     ssh-keyscan -H echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts

      - name: SSH into remote Server and execute eommand
        run: |
          cd ~/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          ssh-keygen -f key.pem -y > key.pub
          ssh-keygen -l -f key.pub
          echo "${{ secrets.PASSPHRASE }}" | \
          ssh -i key.pem  -o "StrictHostKeyChecking no" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} whoami
