name: SSH into remote server

# on:
#   workflow_run:
#     workflows: ["Spin up a runner"]
#     types:
#       - completed
on:
  - push
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest #using latest ubuntu to build application
    steps:
      # - name: executing remote ssh commands using ssh key
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     script: |
      #         cd ~/ustream
      #         pm2 status

      # - name: Set Up SSH
      #   run: |
      #     mkdir -p ~/.ssh
      #     ls ~/.ssh -al
      #     ssh-keyscan -H echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts
      # - name: Execute command on server
      #   run: |
      #     echo "${{ secrets.PASSPHRASE }}" | \
      #     mkdir -p ~/.ssh
      #     eval `ssh-agent -s`
      #     ssh-add <(echo "${SSH_PRIVATE_KEY}" | base64 --decode | tr -d "\r")
      #     ssh-keyscan -H echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts

      - name: Add SSH key to agent
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/private.key
          sudo chmod 400 ~/.ssh/private.key
          echo 'echo ${{secrets.PASSPHRASE}}' > ~/.ssh/passphrase && chmod 700 ~/.ssh/passphrase
          ls -al ~/.ssh
          echo "ssh auth socket: $SSH_AUTH_SOCK"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'Add the PASS'
          echo "$PASSPHRASE" > ~/.passphrase && chmod +x ~/.passphrase
          echo "create known_hosts"
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ls -al ~/
          echo 'Add ssh key'
          cat ~/.ssh/private.key | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh/passphrase ssh-add - >/dev/null
          ssh-add -l

      - name: SSH into remote Server and execute eommand
        run: |
          echo "SSH to remote server"
          ssh -tt -i ~/.ssh/private.key  -o "StrictHostKeyChecking no" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          echo "Done"
          pwd
