name: SSH into remote server

on:
  workflow_run:
    workflows: ["Spin up a runner"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up SSH
        run: |
          echo "${{ secrets.PASSPHRASE }}" | \
          mkdir -p ~/.ssh
          (echo "${{SSH_PRIVATE_KEY}}" | base64 -d) > ~/.ssh/id_rsa
          eval `ssh-agent -s`
          ssh-add < (echo "${{SSH_PRIVATE_KEY}}" | base64 -d)
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH into remote Server and execute eommand
        run: |
          echo "${{ secrets.PASSPHRASE }}" | \
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "Hello from GitHub Actions!"'
