name: SSH into remote server

# on:
#   workflow_run:
#     workflows: ["Spin up a runner"]
#     types:
#       - completed
on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          ls ~/.ssh -al
          eval `ssh-agent -s`
          echo "${SSH_PRIVATE_KEY}" | base64 --decode | tr -d "\r" | ssh-add - > /dev/null
      #   run: |
      #     echo "${{ secrets.PASSPHRASE }}" | \
      #     mkdir -p ~/.ssh
      #     eval `ssh-agent -s`
      #     ssh-add <(echo "${SSH_PRIVATE_KEY}" | base64 --decode | tr -d "\r")
      #     ssh-keyscan -H echo "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts

      # - name: SSH into remote Server and execute eommand
      #   run: |
      #     echo "${{ secrets.PASSPHRASE }}" | \
      #     ssh -i ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "Hello from GitHub Actions!"'
